server:
  port: 8080


---

spring:
  profiles: default
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#  datasource:
#    url: jdbc:mysql://${DATASORUCE_ADDRESS:35.221.110.118:3306}/${DATASORUCE_TABLESPACE:my-database}
#    username: ${DATASORUCE_USERNAME:root}
#    password: ${DATASORUCE_PASSWORD:secretpassword}
#    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8088
---
spring:
  profiles: docker
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#  datasource:
#    url: jdbc:mysql://${DATASORUCE_ADDRESS:35.221.110.118:3306}/${DATASORUCE_TABLESPACE:my-database}
#    username: ${DATASORUCE_USERNAME:root}
#    password: ${DATASORUCE_PASSWORD:secretpassword}
#    driverClassName: com.mysql.cj.jdbc.Driver